import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en"
            data-theme="dark"
            className={`${geistSans.variable} ${geistMono.variable} h-full dark antialiased`} >
            <body className="min-h-full flex flex-col">
                <Navbar />
                <main>{children}</main>
                <Footer />
                
                <Toaster
                    position="top-center"
                    toastOptions={{
                        duration: 3000,
                        style: {
                            background: "#111",
                            color: "#fff",
                            border: "1px solid rgba(255,255,255,0.12)",
                        },
                        success: {
                            iconTheme: {
                                primary: "#a855f7",
                                secondary: "#fff",
                            },
                        },
                    }}
                />
            </body>

        </html>
    );
}
